@startuml
interface Visitable{
+accept(v: Visitor): void
}
interface Visitor{
+visit(f: VariableFunction): void
+visit(f: NonVariableFunction): void
+visit(p: MultipleParameter): void
+visit(p: SingleParameter): void
+visit(p: Constant): void
+visit(o: AbsoluteValue): void
+visit(o: SquareRoot): void
+visit(o: Addition): void
+visit(o: Subtraction): void
+visit(o: Product): void
}

class Printer implements Visitor{
+visit(f: VariableFunction): void
+visit(f: NonVariableFunction): void
+visit(p: Variable): void
+visit(p: Constant): void
+visit(o: AbsoluteValue): void
+visit(o: SquareRoot): void
+visit(o: Addition): void
+visit(o: Subtraction): void
+visit(o: Product): void
}


interface Function extends Visitable{
+eval(): Double
+listVariables(): List<String>
}
class VariableFunction implements Function{
-variable: Parameter
-operation: Operation
+eval(): Double
+listVariables(): List<String>
+accept(v: Visitor): void
}
class NonVariableFunction implements Function{
-operation: Operation
+eval(): Double
+listVariables(): List<String>
+accept(v: Visitor): void
}

interface Parameter extends Visitable{
+getValue(): MathNumber
+setValue(value: MathNumber): void
}

class Variable implements Parameter{
-variableName: String
-value: MathNumber
+getValue(): MathNumber
+setValue(value: MathNumber): void
}

class Constant implements Parameter{
-value: MathNumber
+getValue(): MathNumber
+setValue(value: MathNumber): void
}

interface Operation extends Visitable, Parameter{
+solve(): Double
}

abstract class UnaryOperation implements Operation{
-parameter: Parameter
+solve(): Double
+accept(v: Visitor): void
+getValue(): MathNumber
+setValue(value: MathNumber): void
}

abstract class BinaryOperation implements Operation{
-first: Parameter
-second: Parameter
-operand: String
+solve(): Double
+accept(v: Visitor): void
+getValue(): MathNumber
+setValue(value: MathNumber): void
}

class Addition extends BinaryOperation{
+solve(): Double
+accept(v: Visitor): void
}
class Subtraction extends BinaryOperation{
+solve(): Double
+accept(v: Visitor): void
}
class Product extends BinaryOperation{
+solve(): Double
+accept(v: Visitor): void
}
class Division extends BinaryOperation{
+solve(): Double
+accept(v: Visitor): void
}
class Power extends BinaryOperation{
+solve(): Double
+accept(v: Visitor): void
}

class AbsoluteValue extends UnaryOperation{
+solve(): Double
+accept(v: Visitor): void
}
class SquareRoot extends UnaryOperation{
+solve(): Double
+accept(v: Visitor): void
}

class Number {
//Java built-in Number class
}

class MathNumber extends Number{
-value: Number
+toString(): String
+intValue(): int
+longValue(): long
+floatValue(): float
+doubleValue(): double
}



' Functions receive ONE WORD OR LETTER,
' then they are single-variable

' Extras
Visitable <-Visitor
Variable o-- MathNumber
Constant o-- MathNumber


@enduml